Repository ethereumjs/rlp, pull requests merged in 2022-01, with the labels that each got.

#95 Improve cli interface
  README.md
  bin/rlp
  test/integration.spec.ts
Labels: PR state: needs review

#108 Readme and typedoc updates, normalize source error messages to capital RLP
  README.md
  package.json
  src/index.ts
  test/dataTypes.spec.ts
  test/integration.spec.ts
Labels: type: docs, PR state: needs review

#90 Add browser support, remove dependencies
  README.md
  bin/rlp
  package-lock.json
  package.json
  src/index.ts
  src/types.ts
  test/dataTypes.spec.ts
  test/integration.spec.ts
  test/invalid.spec.ts
  test/official.spec.ts
  test/utils.ts
  tsconfig.browser.json
  tsconfig.json
Labels: type: refactor, PR state: needs review

#109 Fix karma, readme updates, combine source to one file
  .eslintrc.js
  .github/workflows/build.yml
  .gitignore
  CHANGELOG.md
  README.md
  bin/rlp
  package-lock.json
  package.json
  src/index.ts
  src/types.ts
  test/dataTypes.spec.ts
  test/invalid.spec.ts
  test/official.spec.ts
  test/utils.ts
  tsconfig.browser.json
  tsconfig.prod.json
Labels: type: refactor, type: docs, PR state: needs review
